apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: myeks01
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: myeks01-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: myeks01-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: myeks01-control-plane
  namespace: default
spec:
  region: us-east-1
  sshKeyName: myeks01
  version: v1.29
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: myeks01-pool-0
  namespace: default
spec:
  clusterName: myeks01
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: myeks01
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: myeks01-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: myeks01-pool-0
  namespace: default
spec: {}
