apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: capi-eks-argo
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: capi-eks-argo-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: capi-eks-argo-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-argo-control-plane
  namespace: default
spec:
  region: us-east-1
  sshKeyName: capi-eks-argo
  version: v1.22.6
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachinePool
metadata:
  name: capi-eks-argo-pool-0
  namespace: default
spec:
  clusterName: capi-eks-argo
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: capi-eks-argo
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: capi-eks-argo-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: capi-eks-argo-pool-0
  namespace: default
spec: {}
